server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico)$ {
        try_files $uri =404;
    }
}

# server {
#     listen 80;
#     server_name localhost;

#     location / {
#         return 200 'Hello from Ansible-managed Nginx!';
#         add_header Content-Type text/plain;
#     }
# }