upstream interio_backend {
    # Load balancing algorithm
    least_conn;                    # sends to least busy server

    server interio;   
    server dreamy;   
    server droll;   

    # Reduce timeout for faster failure detection
    keepalive 32;


}

server {
    listen 80;
    server_name _;

    # Timeout settings
    proxy_connect_timeout 5s;    
    proxy_send_timeout 10s;
    proxy_read_timeout 10s;

    location / {
        proxy_pass http://interio_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# # /etc/nginx/conf.d/production.conf
# # Main reverse proxy — sits in front of containers

# upstream backend {
#     least_conn;                        # load balance strategy
#     server 127.0.0.1:8081 weight=3;   # container 1
#     server 127.0.0.1:8082 weight=3;   # container 2
#     server 127.0.0.1:8083 weight=3;   # container 3
#     keepalive 32;
# }

# server {
#     listen 80;
#     server_name lb.local;

#     # Security headers
#     add_header X-Frame-Options "SAMEORIGIN";
#     add_header X-Content-Type-Options "nosniff";
#     add_header X-XSS-Protection "1; mode=block";

#     # Proxy to backend containers
#     location / {
#         proxy_pass http://backend;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     }

#     # Cache static assets
#     location ~* \.(jpg|css|js|png|gif)$ {
#         expires 30d;
#         add_header Cache-Control "public, no-transform";
#     }

#     # Block hidden files
#     location ~ /\. {
#         deny all;
#     }
# }