pipeline {

    agent any

    environment {
        DOCKER_REGISTRY = 'santonix'
        VERSION         = "1.0.${BUILD_NUMBER}"
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timestamps()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                sh 'git log --oneline -3'
                echo "✅ Checkout complete — build #${BUILD_NUMBER}"
            }
        }

    }

    post {
        success { echo "✅ Stage 1 passed!" }
        failure { echo "❌ Stage 1 failed!" }
    }
}
