# inventory/hosts.yml
all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 127.0.0.1
          ansible_port: 2221
          ansible_user: root           # SSH user inside the container
          ansible_password: root       # SSH password (matches what you set in Docker)
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          http_port: 80
        web2:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: root
          ansible_password: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          http_port: 8080
    databases:
      hosts:
        db1:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: root
          ansible_password: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          db_port: 3306